# 01. Tensor Operations

Welcome to the fundamental building blocks of deep learning: **tensors**. In this notebook, you'll learn what tensors are, why they're important, and how to manipulate them using PyTorch.


## Why Tensors Matter

Before we dive into the technical details, let's understand why tensors are so important in machine learning:

1. **Efficient Numerical Computation**: Tensors allow for efficient mathematical operations across large datasets.
2. **GPU Acceleration**: Tensor operations can easily be moved to GPUs for massive performance gains.
3. **Automatic Differentiation**: Modern deep learning frameworks use tensors to automatically calculate gradients.
4. **Dimensionality**: They can represent complex data with multiple dimensions (images, videos, text, etc.).

By the end of this notebook, you'll have a solid foundation in tensor operations, which is essential for understanding more advanced deep learning concepts.


## Tensors

In this section, we will learn about **tensors** and how they are used in PyTorch.

Tensors are the fundamental building block of machine learning, and they represent data in a numerical way.

Let's say we need to represent the a _gray_ image of the number `2` as a tensor with height and width of 16 pixels. The tensor shape would be `[1, 16, 16]`, which means:

- 1: color_channels
- 16: height
- 16: width

> Note: The color_channels is `1` because the image is gray. If the image is colored, it would have `3` color channels (red, green and blue).


### Grayscale Image

Let's represent the grayscale image for the number `2`.

Here the tensor representation has the following shape: `[1, height, width]`.

<img src="../09_images/01-digit.png" alt="Digit image" width="400" height="400">


### Colored Image

Below is a colored image.

The tensor representation has the following shape: `[3, height, width]`.

<img src="../09_images/01-rgb_image.png" alt="Colored image" width="800">


### Creating tensors

PyTorch provides a whole documentation page dedicated to the [torch.Tensor](https://docs.pytorch.org/docs/stable/tensors.html) class.

Below is a table summarizing the types of tensors, which will write next in code.

| Name   | What is It?                      | Number of Dimensions |
| ------ | -------------------------------- | -------------------- |
| scalar | A single number                  | 0                    |
| vector | A list of numbers                | 1                    |
| matrix | A 2-dimensional array of numbers | 2                    |
| tensor | A n-dimensional array of numbers | 0+                   |

<img src="../09_images/01-scalar-vector-matrix-tensor.png" alt="Tensor types" width="800">

Now let's go through each of these types of tensors in code.


#### Scalar


In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Check versions for reference
print(f"PyTorch version: {torch.__version__}")
print(f"NumPy version: {np.__version__}")

# Check if CUDA is available
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")

# Create a simple scalar tensor
scalar = torch.tensor(7)
scalar

PyTorch version: 2.7.1
NumPy version: 2.3.1
CUDA available: False


tensor(7)

In [2]:
print(f"Scalar Dimensions: {scalar.ndim}")
print(f"Scalar Item: {scalar.item()}")

Scalar Dimensions: 0
Scalar Item: 7


#### Vector

A vector can contain a list of numbers.

You could have a vector `[5, 6]` to represent `[cars, bikes]` or `[5, 6, 7]` to represent `[cars, bikes, trucks]`.


In [3]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

You can tell the number of dimensions of a tensor by the number of `[` it has on the outside.


In [4]:
print(f"Vector Dimensions: {vector.ndim}")
print(f"Vector Shape: {vector.shape}")

Vector Dimensions: 1
Vector Shape: torch.Size([2])


#### Matrix


In [5]:
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [6]:
print(f"Matrix Dimensions: {matrix.ndim}")
print(f"Matrix Shape: {matrix.shape}")

Matrix Dimensions: 2
Matrix Shape: torch.Size([2, 2])


#### Tensor


In [7]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [8]:
print(f"Tensor Dimensions: {tensor.ndim}")
print(f"Tensor Shape: {tensor.shape}")

Tensor Dimensions: 3
Tensor Shape: torch.Size([2, 2, 3])


#### Zeros and Ones

You can create tensors filled with zeros or ones using the `torch.zeros` and `torch.ones` functions.

Sometimes you need to create a tensor filled with zeros or ones, for example, when initializing weights in a neural network, or when you need masks for certain operations like image segmentation.


In [9]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Range and Tensors Like

Sometimes you need to create a tensor with a range of numbers, or a tensor that has the same shape as another tensor.


In [11]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
print(f"Zero to Ten: {zero_to_ten}")

ten_zeros = torch.zeros_like(zero_to_ten)
print(f"Ten Zeros: {ten_zeros}")

ten_ones = torch.ones_like(zero_to_ten)
print(f"Ten Ones: {ten_ones}")

Zero to Ten: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Ten Zeros: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Ten Ones: tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


#### Tensor Data Types

The most common data types for tensors are:

- `torch.float32` (32-bit floating point)
- `torch.float64` (64-bit floating point)
- `torch.int32` (32-bit integer)
- `torch.int64` (64-bit integer)
- `torch.uint8` (8-bit unsigned integer)

The reason for having different data types is to save memory and to speed up computations.

For example, if you have a tensor that contains only integers, you can use `torch.int32` or `torch.int64` instead of `torch.float32` or `torch.float64`, which would take more memory and be slower to compute.

The higher the precision of the data type, the more memory it takes and the slower it is to compute. So lower precision data types are generally faster to compute and use less memory, but they may not be suitable for all operations, especially those that require high precision.

This matters in deep learning, where you have a lot of data and a lot of computations to do.

> Resources:
>
> - [PyTorch Tensor Data Types](https://pytorch.org/docs/stable/tensors.html#data-types)
> - [Precision (computer science)](<https://en.wikipedia.org/wiki/Precision_(computer_science)>)


### Moving Tensors to GPU

One of the most powerful features of PyTorch is the ability to move tensors between different devices (CPU and GPU). This is crucial for deep learning, as GPUs can significantly accelerate tensor operations.

> Note: This section is still helpful to understand even if you don't have a GPU on your machine.


In [12]:
# Define device (will use CUDA if available, otherwise CPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Create a tensor
cpu_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"CPU Tensor: {cpu_tensor}, Device: {cpu_tensor.device}")

# Move tensor to specified device (GPU if available)
device_tensor = cpu_tensor.to(device)
print(f"Device Tensor: {device_tensor}, Device: {device_tensor.device}")

# Operations on device tensor
device_tensor_plus_one = device_tensor + 1
print(f"Device Tensor + 1: {device_tensor_plus_one}")

# Note: When using tensors on different devices, they need to be on the same device for operations
try:
    result = (
        cpu_tensor + device_tensor
    )  # This will cause an error if device_tensor is on GPU
except RuntimeError as e:
    print(f"Error: {e}")
    print("\nTo fix this, move tensors to the same device before operations:")
    result = cpu_tensor + device_tensor.cpu()  # Move GPU tensor back to CPU
    print(f"Result after fixing: {result}")

# Performance Note
print("\nNote: For small operations like this, you won't see performance benefits.")
print("GPU acceleration shows its value with large matrices and deep learning models.")

Using device: cpu
CPU Tensor: tensor([1., 2., 3., 4.]), Device: cpu
Device Tensor: tensor([1., 2., 3., 4.]), Device: cpu
Device Tensor + 1: tensor([2., 3., 4., 5.])

Note: For small operations like this, you won't see performance benefits.
GPU acceleration shows its value with large matrices and deep learning models.


In [13]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
print(f"Float 32 Tensor: {float_32_tensor}")
print(f"Float 32 Tensor Data Type: {float_32_tensor.dtype}")

Float 32 Tensor: tensor([3., 6., 9.])
Float 32 Tensor Data Type: torch.float32


In [14]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
print(f"Float 16 Tensor: {float_16_tensor}")
print(f"Float 16 Tensor Data Type: {float_16_tensor.dtype}")

Float 16 Tensor: tensor([3., 6., 9.], dtype=torch.float16)
Float 16 Tensor Data Type: torch.float16


### Tensor Operations

In deep learning, data is often represented as tensors, and you need to perform various operations on these tensors.

These operations include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

There are more, but these are the most common ones you'll use in deep learning.


#### Basic Operations

In this section, we'll cover the basic operations you can perform on tensors like addition, subtraction, multiplication, and division.


In [15]:
tensor = torch.tensor([1, 2, 3])

print(f"Tensor: {tensor}")
print(f"Addition: {tensor + 1}")
print(f"Subtraction: {tensor - 1}")
print(f"Multiplication: {tensor * 10}")
print(f"Division: {tensor / 2}")

Tensor: tensor([1, 2, 3])
Addition: tensor([2, 3, 4])
Subtraction: tensor([0, 1, 2])
Multiplication: tensor([10, 20, 30])
Division: tensor([0.5000, 1.0000, 1.5000])


#### Matrix Multiplication

Matrix multiplication is a fundamental operation in deep learning, especially in neural networks. For more information, you can refer to the following links:

- [Matrix Multiplication Math is Fun page](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
- [Matrix Multiplication Wikipedia page](https://en.wikipedia.org/wiki/Matrix_multiplication)

PyTorch provides a `torch.matmul` function to perform matrix multiplication. The `@` operator is also available for this purpose.

There are two main rules for matrix multiplication:

1. The **inner dimensions** must match:
   - `(3, 2) @ (2, 4)` is valid because the inner dimensions `2` match.
   - `(3, 2) @ (3, 4)` is invalid because the inner dimensions `2` and `3` do not match.
2. The resulting matrix will have the shape of the **outer dimensions**:
   - `(3, 2) @ (2, 4)` results in a matrix of shape `(3, 4)`.
   - `(3, 2) @ (2, 3)` results in a matrix of shape `(3, 3)`.

For more information on matrix multiplication, you can refer to the [PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).

If you would like to visualize the matrix multiplication, you can use the [Matrix Multiplication Visualizer](https://matrixmultiplication.xyz/).


In [16]:
tensor = torch.tensor([1, 2, 3])

print((f"Matrix Multiplication: {torch.matmul(tensor, tensor)}"))

Matrix Multiplication: 14


It's important to note that PyTorch uses `numpy` under the hood for many of its operations. You can do the matrix multiplication by hand, but it's much easier to use the built-in functions provided by PyTorch since it optimizes performance and memory usage.

The built-in `torch.matmul` function is faster.


In [17]:
tensor = torch.arange(start=0, end=100, step=1)

In [18]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

CPU times: user 1.2 ms, sys: 1.3 ms, total: 2.5 ms
Wall time: 3.48 ms


tensor(328350)

In [19]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 36 μs, sys: 4 μs, total: 40 μs
Wall time: 44.1 μs


tensor(328350)

### Shape Errors

One of the most common errors you'll encounter when working with tensors is a shape error. This happens when you try to perform an operation on tensors that have incompatible shapes.


In [20]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)

# Run the cell to see the error
# torch.matmul(tensor_A, tensor_B)

The error message will look something like this: `ValueError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)`.

We need to make sure that the inner dimensions match when performing matrix multiplication. In this case, we can fix the shapes by transposing one of the tensors.

We can use the `torch.transpose` or `tensor.T` function to do this.


In [21]:
print(f"Tensor A: {tensor_A}")
print(f"Tensor B: {tensor_B}")
print(f"Tensor A Shape: {tensor_A.shape}")
print(f"Tensor B Shape: {tensor_B.shape}")

Tensor A: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Tensor B: tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
Tensor A Shape: torch.Size([3, 2])
Tensor B Shape: torch.Size([3, 2])


In [22]:
print(f"Tensor A Shape: {tensor_A.shape}")
print(f"Tensor B Shape: {tensor_B.T.shape}")

Tensor A Shape: torch.Size([3, 2])
Tensor B Shape: torch.Size([2, 3])


In [23]:
print(f"Original Shapes:\nTensor A: {tensor_A.shape}\nTensor B: {tensor_B.shape}\n")
# Transpose Tensor B
tensor_B_T = tensor_B.T
print(f"Transposed Shapes:\nTensor A: {tensor_A.shape}\nTensor B: {tensor_B_T.shape}\n")

matmul_output = torch.matmul(tensor_A, tensor_B_T)
print(f"Matrix Multiplication Output:\n{matmul_output}")
print(f"Output Shape: {matmul_output.shape}")

Original Shapes:
Tensor A: torch.Size([3, 2])
Tensor B: torch.Size([3, 2])

Transposed Shapes:
Tensor A: torch.Size([3, 2])
Tensor B: torch.Size([2, 3])

Matrix Multiplication Output:
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output Shape: torch.Size([3, 3])


#### Aggregation Operations

Aggregation operations are used to compute a single value from a tensor, such as the sum, mean, or maximum value. These operations are useful for summarizing data and extracting important features.


In [24]:
x = torch.arange(start=0, end=100, step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
print(f"Minimum Value: {x.min()}")
print(f"Maximum Value: {x.max()}")
# print(f"Mean Value: {x.mean()}") # This will raise an error because the mean function expects a float tensor
print(f"Mean Value: {x.float().mean()}")
print(f"Sum Value: {x.sum()}")

Minimum Value: 0
Maximum Value: 90
Mean Value: 45.0
Sum Value: 450


In [26]:
# An alternative is using `torch` methods
print(f"Minimum Value: {torch.min(x)}")
print(f"Maximum Value: {torch.max(x)}")
print(f"Mean Value: {torch.mean(x.float())}")
print(f"Sum Value: {torch.sum(x)}")

Minimum Value: 0
Maximum Value: 90
Mean Value: 45.0
Sum Value: 450

Maximum Value: 90
Mean Value: 45.0
Sum Value: 450


#### Positional Min and Max

We can also find the position of the minimum and maximum values in a tensor using the `torch.min` and `torch.max` functions.

These functions return both the value and the index of the minimum or maximum value in the tensor.


In [27]:
tensor = torch.arange(start=10, end=100, step=10)
print(f"Tensor: {tensor}")

print(f"Index of Minimum Value: {torch.argmin(tensor)}")
print(f"Index of Maximum Value: {torch.argmax(tensor)}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index of Minimum Value: 0
Index of Maximum Value: 8
Index of Minimum Value: 0
Index of Maximum Value: 8


#### Changing Tensor Datatype

We can change the data type of a tensor using the `tensor.type()` method or by using the `tensor.to()` method. This is useful when you need to perform operations that require a specific data type, such as converting an integer tensor to a float tensor for mathematical operations.


In [28]:
tensor = torch.arange(start=0.0, end=100.0, step=10.0)
print(f"Tensor Data Type: {tensor.dtype}")

tensor_float16 = tensor.type(torch.float16)
print(f"Tensor Float16 Data Type: {tensor_float16.dtype}")

tensor_int8 = tensor.type(torch.int8)
print(f"Tensor Int8 Data Type: {tensor_int8.dtype}")

Tensor Data Type: torch.float32
Tensor Float16 Data Type: torch.float16
Tensor Int8 Data Type: torch.int8


#### Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

Reshaping, stacking, squeezing, and unsqueezing tensors are common operations in deep learning. These operations allow you to change the shape of a tensor, combine multiple tensors, or add/remove dimensions.

Below is a table summarizing these operations:
| Operation | Description |
| ----------- | --------------------------------------------------------------------------------------------- |
| Reshape | Change the shape of a tensor without changing its data. |
| View | Create a new tensor that shares the same data as the original tensor but with a different shape. |
| Stack | Combine multiple tensors along a new dimension. |
| Squeeze | Remove dimensions of size 1 from a tensor. |
| Unsqueeze | Add a dimension of size 1 to a tensor. |
| Permute | Change the order of dimensions in a tensor. |

> Note: The `view` operation really only creates a new view of the same tensor. Changing the view changes the original tensor as well. This is different from `reshape`, which creates a new tensor with the same data but a different shape.


In [29]:
x = torch.arange(start=1.0, end=8.0, step=1.0)
print(f"Tensor: {x}")
print(f"Tensor Shape: {x.shape}")

# Add extra dimension
x_reshaped = x.reshape(1, 7)
print(f"\nReshaped Tensor: {x_reshaped}")
print(f"Reshaped Tensor Shape: {x_reshaped.shape}")

# Change View
z = x.view(1, 7)
print(f"\nView Tensor: {z}")
print(f"View Tensor Shape: {z.shape}")

# Stack Tensors
x_stacked = torch.stack([x, x, x, x], dim=0)  # Change dim to 1 and see the difference
print(f"\nStacked Tensor: {x_stacked}")
print(f"Stacked Tensor Shape: {x_stacked.shape}")

# Squeeze
x_squeezed = x_reshaped.squeeze()
print(f"\nSqueezed Tensor: {x_squeezed}")
print(f"Squeezed Tensor Shape: {x_squeezed.shape}")

# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nUnsqueezed Tensor: {x_unsqueezed}")
print(f"Unsqueezed Tensor Shape: {x_unsqueezed.shape}")

Tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Tensor Shape: torch.Size([7])

Reshaped Tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Reshaped Tensor Shape: torch.Size([1, 7])

View Tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
View Tensor Shape: torch.Size([1, 7])

Stacked Tensor: tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])
Stacked Tensor Shape: torch.Size([4, 7])

Squeezed Tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Squeezed Tensor Shape: torch.Size([7])

Unsqueezed Tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Unsqueezed Tensor Shape: torch.Size([1, 7])


In [30]:
# Permute
x_original = torch.rand(size=(224, 224, 3))
print(f"Original Tensor Shape: {x_original.shape}")

x_permuted = x_original.permute(
    2, 0, 1
)  # Shifts axis order from (224, 224, 3) to (3, 224, 224)
print(f"Permuted Tensor Shape: {x_permuted.shape}")

Original Tensor Shape: torch.Size([224, 224, 3])
Permuted Tensor Shape: torch.Size([3, 224, 224])


### Selecting Data From Tensors (Indexing)

Indexing is a powerful feature in PyTorch that allows you to select specific elements or slices from a tensor. This is similar to how you would index into a list or an array in Python.

You can use indexing to access specific elements, slices, or even entire dimensions of a tensor. This is useful for extracting features, manipulating data, or performing operations on specific parts of a tensor.


In [31]:
x = torch.arange(1, 10).reshape(1, 3, 3)

print(f"Original Tensor: {x}")
print(f"Original Tensor Shape: {x.shape}")

Original Tensor: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Original Tensor Shape: torch.Size([1, 3, 3])


In [32]:
print(f"First Square Bracket: {x[0]}")
print(f"Second Square Bracket: {x[0][0]}")
print(f"Third Square Bracket: {x[0][0][0]}")

First Square Bracket: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second Square Bracket: tensor([1, 2, 3])
Third Square Bracket: 1


In [33]:
print(f"All values in the first dimension: {x[:, 0, 0]}")
print(f"All values in the second dimension: {x[0, :, 0]}")
print(f"All values in the third dimension: {x[0, 0, :]}")
print(f"All values in the first and second dimensions: {x[:, :, 0]}")
print(f"All values in the first and third dimensions: {x[:, 0, :]}")
print(f"All values in the second and third dimensions: {x[0, :, :]}")

All values in the first dimension: tensor([1])
All values in the second dimension: tensor([1, 4, 7])
All values in the third dimension: tensor([1, 2, 3])
All values in the first and second dimensions: tensor([[1, 4, 7]])
All values in the first and third dimensions: tensor([[1, 2, 3]])
All values in the second and third dimensions: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Extra Reading

- [What's a Tensor?](https://www.youtube.com/watch?v=f5liqUk0ZTw)
- [PyTorch Tensors: A Deeper Dive](https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)
